services:
  postgres:
    image: postgres:15-alpine
    container_name: time_tracker_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../db/migrations:/docker-entrypoint-initdb.d
    networks:
      - time_tracker_network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: timetracker_backend
    restart: always
    environment:
      DB_HOST: postgres
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
    ports:
      - "8005:8005"
    depends_on:
      - postgres
    networks:
      - time_tracker_network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: timetracker_frontend
    restart: always
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - time_tracker_network

volumes:
  pgdata:

networks:
  time_tracker_network:
    driver: bridge
